# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Nodeum
  fr: Nodeum
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: /pages/accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
buttons:
    documentation:
        en: See the full documentation
        fr: Voir la documentation
    contact:
        en: Contact us
        fr: Nous contacter
    trial:
        en: Get the free trial
        fr: Utilisez la demo gratuite
scroll:
    en: Scroll for more
    fr: Veuillez scroller
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
future: true

# Build settings
markdown: kramdown
